# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OlGeFpvTGANxE3FsEO6nP3F6sLtajalu
"""

from transformers import pipeline
import gradio as gr

"""Loading a Pre-Trained Conversational Model"""

chatbot = pipeline("text-generation", model="microsoft/DialoGPT-medium")

"""Creating the chatbot Logic"""

def chat_response(user_input):
    response = chatbot(user_input, max_new_tokens=200, pad_token_id=50256)
    generated_text = response[0]["generated_text"]
    # Strip the input prompt from the start of the generated text
    reply = generated_text[len(user_input):].strip()
    return reply if reply else "I'm not sure how to respond to that."

"""Deploying with Gradio"""

iface = gr.Interface(
    fn=chat_response,
    inputs = "text",
    outputs = "text",
    title = "AI Chatbot",
    description = "Ask anything you want"
)
iface.launch()

